### ISSUE TITLE
Calibre doesn't open the plugin

### ISSUE THREAD

**Issue by Rayan5623** [DRKSLV/calibreBionicReading#2]
Hi, 
It's not a very big issue but, can you archive the sources files into the archive without adding them into a subfolder ? 

I've lost more or less 20 minutes to understand that Calibre didn't recognize the plugin because the init.py file was wrapped into another folder, 
So the solution was easy, i unzipped the files and i compressed them in another archive and that worked

**Comment by kartonrad** [comment]
Ah yeah, the .zip that github generates is no good

I always zipped it manually, or called the cli function to load it directly

I'll try to upload a good zip later
